name: check264
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cycler=0.10.0
  - freetype=2.9.1
  - future=0.18.2
  - intel-openmp=2019.4
  - joblib=0.14.1
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - llvm-openmp=4.0.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1
  - pandas=1.0.1
  - patsy=0.5.1
  - pip=20.0.2
  - pylogit=0.2.2
  - pyparsing=2.4.6
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.43.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
prefix: /Users/tbrathwaite/anaconda2/envs/check264
