name: check264
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - freetype=2.9.1=hb4e5f40_0
  - future=0.18.2=py36_0
  - intel-openmp=2019.4=233
  - joblib=0.14.1=py_0
  - kiwisolver=1.1.0=py36h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h9aa3819_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.15=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - ncurses=6.2=h0a44026_0
  - numpy=1.18.1=py36h7241aed_0
  - numpy-base=1.18.1=py36h6575580_1
  - openssl=1.1.1=h1de35cc_0
  - pandas=1.0.1=py36h6c726b0_0
  - patsy=0.5.1=py36_0
  - pip=20.0.2=py36_1
  - pylogit=0.2.2=py_1
  - pyparsing=2.4.6=py_0
  - python=3.6.10=h359304d_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.22.1=py36h27c97d8_0
  - scipy=1.4.1=py36h9fa6033_0
  - seaborn=0.10.0=py_0
  - setuptools=45.2.0=py36_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=ha441bb4_0
  - statsmodels=0.11.0=py36h1de35cc_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py36h1de35cc_3
  - tqdm=4.43.0=py_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/tbrathwaite/anaconda2/envs/check264

